export const ui = {
  icon: 'block shrink-0',
  brand: 'inline-flex w-fit items-center gap-2.5 font-bold tracking-[-.035em] text-[1.13rem] text-green-deep no-underline',
  brandInverse: 'text-[#f8f8ee] max-[700px]:hidden',
  brandMark: 'grid size-9 place-items-center rounded-[11px] border border-line-strong bg-paper-bright text-green-deep',
  authLayout: 'grid min-h-screen grid-cols-[minmax(360px,.92fr)_minmax(480px,1.08fr)] bg-paper-bright max-[850px]:grid-cols-[minmax(310px,.82fr)_minmax(420px,1.18fr)] max-[700px]:flex max-[700px]:flex-col',
  authIntro: 'relative flex min-h-screen flex-col justify-between overflow-hidden bg-green-dark px-[clamp(34px,5vw,80px)] py-10 text-[#f6f8ef] max-[700px]:min-h-0 max-[700px]:px-6 max-[700px]:py-5',
  authCopy: 'relative z-10 my-auto max-w-[490px] py-16',
  authKicker: 'mb-5 text-[.89rem] font-semibold tracking-[.012em] text-[#bad3bf]',
  authTitle: 'm-0 max-w-[11ch] text-[clamp(2.55rem,4vw,4rem)] font-semibold leading-[1.08] tracking-[-.052em] text-[#f5f7ed] max-[700px]:text-[clamp(1.7rem,7vw,2.35rem)]',
  authDescription: 'mt-6 max-w-[43ch] text-[1.04rem] leading-[1.7] text-[#d4e2d4]',
  authPrinciples: 'relative z-10 grid gap-3 text-[.87rem] text-[#d6e4d6] max-[700px]:hidden',
  authPrinciple: 'flex items-center gap-3',
  authDot: 'size-1.5 rounded-full bg-[#9dc7a5]',
  authPageMark: 'absolute bottom-[15%] right-[11%] grid text-[#f0f8ee]/15 max-[700px]:hidden',
  authFormPanel: 'flex min-h-screen items-center justify-center px-8 py-12 max-[700px]:min-h-0 max-[700px]:flex-1 max-[700px]:items-start max-[700px]:px-6',
  authFormWrap: 'w-full max-w-[420px]',
  authHeading: 'm-0 text-[1.8rem] font-semibold tracking-[-.03em]',
  authFormIntro: 'mb-6 mt-2 text-[.93rem] text-ink-soft',
  authForm: 'grid gap-[18px]',
  fieldLabel: 'grid gap-2 text-[.86rem] font-semibold text-ink-soft',
  fieldInput: 'min-h-12 w-full rounded-lg border border-line-strong bg-paper-bright px-3.5 text-ink outline-none placeholder:text-ink-quiet focus:border-green focus:ring-2 focus:ring-green/15',
  passwordWrap: 'relative block',
  passwordButton: 'absolute inset-y-1 right-1 grid w-10 place-items-center rounded-md text-ink-quiet hover:bg-paper-tint hover:text-green-deep',
  primaryButton: 'inline-flex min-h-12 items-center justify-center gap-3 rounded-lg border border-green-deep bg-green px-4 font-semibold text-white transition hover:bg-green-deep disabled:cursor-not-allowed disabled:opacity-55',
  textButton: 'rounded px-1 py-1 font-semibold text-green-deep underline-offset-4 hover:underline disabled:opacity-50',
  formAlert: 'mb-5 rounded-lg border border-[#e8c8c1] bg-danger-wash p-3 text-[.88rem] leading-relaxed text-danger',
  authSwitch: 'mt-7 flex flex-wrap items-center gap-1 text-sm text-ink-soft',
  authPrivacy: 'mt-7 flex items-center gap-2 text-sm text-ink-quiet',
  authSafety: 'mt-4 max-w-[55ch] text-xs leading-relaxed text-ink-quiet',
  authMobileBrand: 'mb-7 hidden max-[700px]:block',
  telegramPage: 'min-h-screen bg-paper px-6 py-8',
  telegramShell: 'mx-auto max-w-6xl',
  telegramHeader: 'mb-12 flex items-center justify-between border-b border-line pb-5',
  telegramLayout: 'grid grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)] items-start gap-16 max-[850px]:grid-cols-1 max-[700px]:gap-8',
  telegramIntro: 'grid gap-8 py-8',
  telegramMark: 'grid size-12 place-items-center rounded-xl border border-line-strong bg-paper-bright text-green-deep',
  telegramTitle: 'max-w-[16ch] text-[clamp(2rem,4vw,3.3rem)] font-semibold leading-tight tracking-[-.04em]',
  telegramCopy: 'max-w-[60ch] text-lg leading-relaxed text-ink-soft',
  telegramTrust: 'flex max-w-[52ch] items-start gap-3 border-t border-line pt-5 text-sm text-ink-quiet',
  telegramPanel: 'rounded-xl border border-line bg-paper-bright p-7 max-[700px]:p-5',
  telegramPanelHeading: 'mb-6 border-b border-line pb-5',
  telegramSteps: 'grid list-none gap-7 p-0',
  telegramStep: 'grid grid-cols-[32px_1fr] gap-3',
  telegramStepNumber: 'grid size-8 place-items-center rounded-full bg-green-wash font-semibold text-green-deep',
  telegramStepContent: 'grid gap-3',
  telegramFooter: 'mt-7 border-t border-line pt-5',
  appShell: 'grid h-dvh min-h-0 grid-cols-[286px_minmax(0,1fr)] overflow-hidden bg-paper max-[850px]:grid-cols-[258px_minmax(0,1fr)] max-[700px]:block max-[700px]:h-auto max-[700px]:min-h-screen max-[700px]:overflow-visible',
  sidebar: 'sticky top-0 z-40 flex h-dvh min-h-0 min-w-0 flex-col overflow-hidden border-r border-line bg-paper-tint px-[17px] pb-[17px] pt-6 max-[700px]:fixed max-[700px]:bottom-0 max-[700px]:left-0 max-[700px]:top-0 max-[700px]:h-dvh max-[700px]:w-[min(86vw,330px)] max-[700px]:-translate-x-[103%] max-[700px]:pt-[max(20px,env(safe-area-inset-top))] max-[700px]:shadow-xl max-[700px]:transition-transform',
  sidebarOpen: 'max-[700px]:translate-x-0',
  sidebarTop: 'flex min-h-[43px] items-center justify-between px-2',
  sidebarClose: 'hidden max-[700px]:grid',
  newConversation: 'my-8 flex min-h-[46px] w-full items-center gap-2.5 rounded-lg border border-green-deep bg-green px-3 font-semibold text-white transition hover:bg-green-deep disabled:opacity-55',
  historyHeading: 'mb-2 ml-2 flex items-center justify-between',
  historyHeadingText: 'text-[.79rem] font-bold uppercase tracking-wider text-ink-soft',
  iconButton: 'grid size-9 shrink-0 place-items-center rounded-lg text-ink-soft transition hover:border hover:border-line hover:bg-paper-bright hover:text-green-deep disabled:opacity-55',
  historyList: 'grid min-h-0 flex-1 content-start gap-[3px] overflow-x-hidden overflow-y-auto overscroll-contain pb-3 [scrollbar-width:thin] [scrollbar-color:var(--color-line-strong)_transparent]',
  historyItem: 'grid min-w-0 gap-0.5 rounded-lg border border-transparent px-3 py-2.5 text-left text-ink-soft transition hover:border-line hover:bg-paper-bright/70 hover:text-ink',
  historyItemActive: 'border-[#cfdbcf] bg-paper-bright text-green-deep',
  historyItemTitle: 'overflow-hidden text-ellipsis whitespace-nowrap text-[.88rem] font-medium',
  historyItemDate: 'text-[.76rem] tabular-nums text-ink-quiet',
  historyEmpty: 'mx-2 my-3 max-w-[28ch] text-[.84rem] leading-relaxed text-ink-quiet',
  sidebarBottom: 'mt-auto grid gap-3 border-t border-line px-2 pt-[18px]',
  sidebarNote: 'max-w-[28ch] text-[.77rem] leading-relaxed text-ink-quiet',
  telegramButton: 'flex min-h-10 items-center gap-2.5 rounded-md px-1 text-left text-sm text-ink-soft hover:text-green-deep',
  signoutButton: 'flex min-h-10 items-center gap-2.5 rounded-md px-1 text-left text-sm text-ink-soft hover:text-green-deep',
  workspace: 'relative flex h-full min-h-0 min-w-0 flex-col overflow-hidden bg-paper-bright max-[700px]:h-auto max-[700px]:min-h-screen max-[700px]:overflow-visible',
  workspaceHeader: 'flex min-h-[88px] items-center justify-between gap-4 border-b border-line bg-paper-bright px-[clamp(24px,4.5vw,72px)] py-4 max-[700px]:min-h-[72px] max-[700px]:justify-start max-[700px]:gap-2.5 max-[700px]:px-4',
  workspaceTitle: 'min-w-0 flex-1',
  workspaceTitleText: 'overflow-hidden text-ellipsis whitespace-nowrap text-lg font-semibold',
  workspaceSubtitle: 'overflow-hidden text-ellipsis whitespace-nowrap text-sm text-ink-quiet max-[700px]:text-xs',
  memoryBanner: 'flex items-center justify-between gap-4 border-b border-green/20 bg-green-wash px-[clamp(16px,4.5vw,72px)] py-3 max-[700px]:px-4',
  memorySwitch: 'relative inline-flex h-8 w-14 shrink-0 items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-offset-2 disabled:cursor-not-allowed disabled:opacity-60',
  mobileMenu: 'hidden max-[700px]:grid',
  headerNew: 'hidden min-h-10 items-center gap-2 rounded-lg border border-line px-3 font-semibold text-green-deep hover:bg-green-wash min-[1100px]:inline-flex max-[700px]:inline-flex',
  conversationPanel: 'min-h-0 flex-1 overflow-y-auto overscroll-contain px-[clamp(24px,8vw,120px)] py-8 max-[700px]:overflow-visible max-[700px]:px-5 max-[700px]:py-6',
  emptyPage: 'mx-auto grid max-w-[620px] content-center justify-items-start gap-4 py-[clamp(24px,8vh,88px)]',
  emptyMark: 'grid size-14 place-items-center rounded-xl border border-line-strong bg-paper text-green-deep',
  emptyTitle: 'm-0 text-[clamp(1.7rem,3vw,2.25rem)] font-semibold leading-tight tracking-[-.035em]',
  emptyCopy: 'max-w-[54ch] text-[.98rem] leading-relaxed text-ink-soft',
  promptList: 'mt-3 grid w-full gap-2',
  promptButton: 'grid grid-cols-[58px_1fr_18px] items-center gap-3 border-b border-line px-2 py-4 text-left text-ink-soft hover:text-green-deep',
  promptLabel: 'text-[.72rem] font-bold uppercase tracking-wider text-green-deep',
  messageList: 'mx-auto grid w-full max-w-[760px] gap-8 pb-8',
  messageRow: 'grid gap-2 border-b border-line/70 pb-6',
  messageAuthor: 'flex items-center gap-2 text-sm font-semibold text-ink-soft',
  assistantMark: 'grid size-7 place-items-center rounded-lg bg-green-wash text-green-deep',
  userMark: 'grid size-7 place-items-center rounded-full bg-paper-tint text-[.68rem] text-ink-soft',
  messageContent: 'm-0 whitespace-pre-wrap break-words leading-[1.75] text-ink',
  userMessage: 'rounded-xl bg-paper px-4 py-3',
  composerDock: 'shrink-0 border-t border-line bg-paper-bright px-[clamp(16px,5vw,68px)] pb-4 pt-3 max-[700px]:pb-[max(12px,env(safe-area-inset-bottom))]',
  composerWrap: 'mx-auto max-w-[850px]',
  composer: 'rounded-xl border border-line-strong bg-paper-bright p-3 shadow-sm focus-within:border-green',
  composerTextarea: 'max-h-[168px] min-h-12 w-full resize-none bg-transparent px-2 py-2 text-[.96rem] leading-relaxed outline-none placeholder:text-ink-quiet disabled:cursor-not-allowed',
  composerActions: 'flex items-center justify-between gap-3 border-t border-line pt-2',
  composerTools: 'flex min-w-0 items-center gap-2 text-xs text-ink-quiet',
  attachButton: 'grid size-9 shrink-0 place-items-center rounded-lg text-ink-soft hover:bg-paper-tint hover:text-green-deep disabled:opacity-50',
  sendButton: 'grid size-10 shrink-0 place-items-center rounded-lg bg-green text-white hover:bg-green-deep disabled:cursor-not-allowed disabled:opacity-45',
  composerDisclaimer: 'mt-2 text-center text-[.72rem] text-ink-quiet',
  fileList: 'flex flex-wrap gap-2 py-2',
  fileChip: 'inline-flex max-w-full items-center gap-2 rounded-md bg-paper-tint px-2.5 py-1.5 text-xs',
  inlineAlert: 'flex items-center justify-between gap-3 border-b border-danger/20 bg-danger-wash px-4 py-3 text-sm text-danger',
  sessionScreen: 'grid min-h-screen content-center justify-items-center gap-4 bg-paper px-6 text-center text-ink-soft',
  globalAlert: 'fixed inset-x-4 top-4 z-50 mx-auto flex max-w-2xl items-center justify-between gap-4 rounded-lg border border-[#e8c8c1] bg-danger-wash px-4 py-3 text-sm text-danger shadow-lg',
} as const
